spring.application.name=peluquerias-api

# Base de datos
spring.datasource.url=jdbc:postgresql://db.wkhyqournimrvwhqamjn.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=sgE73eR4Skrz30dA

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Puerto
server.port=8080

# JWT
jwt.secret=pelq2024SuperSecretKeyParaJWTQueDebeSerLargaYSegura123456789
jwt.expiration=86400000